// examples/main/Framework.vue
<template>
  <section>
    <header class="header">
      <nav>
        <ol>
          <li><a @click="goto('react app', '/react')">react16 + antd3</a></li>
          <li><a @click="goto('react15 app', '/15react15')">react15 + antd2</a></li>
          <li><a @click="goto('vue app', '/vue')">vue2 + element2 </a></li>
          <li><a @click="goto('wu_vue app', '/wu_vue')">vue2 + element2 (by wu copy examples)</a></li>
          <li><a @click="goto('microvue app', '/microvue')">microvue2 (by wu vuecli)</a></li>
        </ol>
      </nav>
    </header>
    <div v-if="loading">loading</div>
    <div class="appContainer" v-html="content">content</div>
  </section>
</template>

<script>
	export default {
		name: 'framework',
		props: {
			loading: Boolean,
			content: String,
		},
		methods: {
			goto(title, href) {
				window.history.pushState({}, title, href);
			},
		},
	};
</script>

<style scoped lang="scss">
  .header {
    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol;

    > nav > ol {
      margin: 0;
      font-size: 14px;
      color: blue;
      display: flex;
      flex-direction: column;
      padding: 0;

      > li {
        box-sizing: content-box;
        line-height: 20px;
        font-variant: tabular-nums;
        font-feature-settings: "tnum";
        list-style: decimal;
        padding: 0;
        margin: 0;
      }

      a {
        color: blue;
        text-decoration-line: underline;
      }
    }
  }

  .appContainer {
    margin-top: 50px;
  }
</style>

// examples/main/Framework.jsx
/**
 * @author Kuitos
 * @since 2019-05-16
 */

import React from 'react';
import style from './index.less';

export default function Framework(props) {

  const { content, loading } = props;

  function goto(title, href) {
    window.history.pushState({}, title, href);
  }

  function setInterval() {
    window.setInterval(() => {
      console.log('master interval');
    }, 1000);
  }

  return (
    <>
      <header className={style.header}>
        <nav>
          <ol>
            <li><a onClick={() => goto('react app', '/react')}>react16 + antd3</a></li>
            <li><a onClick={() => goto('react15 app', '/15react15')}>react15 + antd2</a></li>
            <li><a onClick={() => goto('vue app', '/vue')}>vue2 + element2</a></li>
            <li><a onClick={() => goto('wu_vue app', '/wu_vue')}>vue2 + element2(by wu copy examples)</a></li>
            <li><a onClick={() => goto('microvue app', '/microvue')}>microvue2 (by wu vuecli)</a></li>
          </ol>
        </nav>
      </header>
      {loading ? <div>loading...</div> : null}
      <div dangerouslySetInnerHTML={{ __html: content }} className={style.appContainer}/>
    </>

  );
}
